# Generated by Django 3.2.2 on 2022-01-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название аккаунта')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кабинета')),
                ('pixel', models.CharField(blank=True, max_length=99, null=True, verbose_name='Пиксель кабинета')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='описание')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.account')),
            ],
            options={
                'verbose_name': 'Рекламный кабинет',
                'verbose_name_plural': 'Рекламные кабинеты',
            },
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Статуст кампании')),
            ],
            options={
                'verbose_name': 'Cтатус кампании',
                'verbose_name_plural': 'Cтатусы кампаний',
            },
        ),
        migrations.CreateModel(
            name='CodeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='Пример кода')),
                ('html_code', models.TextField(blank=True, verbose_name='Html код')),
                ('css_code', models.TextField(blank=True, verbose_name='Css код')),
                ('js_code', models.TextField(blank=True, verbose_name='Js код')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название страны')),
                ('name_eng', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название страны ENG')),
                ('short_name', models.CharField(max_length=10, verbose_name='Абревивтура страны')),
                ('phone_code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Код мобильного страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, unique=True, verbose_name='название домена')),
                ('beget_id', models.IntegerField(unique=True, verbose_name='id домена на beget')),
                ('description', models.TextField(blank=True, max_length=999, verbose_name='доп. информация')),
                ('facebook', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
                ('google', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
                ('tiktok', models.CharField(choices=[('NEW', 'Новый'), ('USE', 'Запускался'), ('BAN', 'Забанен')], default='NEW', max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя баера')),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, max_length=2, null=True, verbose_name='Страна')),
                ('comm', models.CharField(blank=True, max_length=50, null=True, verbose_name='коментарий')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='цена')),
                ('offer_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='id оффера')),
                ('flow_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='id потока')),
                ('domain', models.CharField(blank=True, max_length=60, null=True, verbose_name='домен лида')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления лида')),
                ('ip', models.CharField(blank=True, max_length=30, null=True, verbose_name='ip address')),
                ('pp_name', models.CharField(blank=True, max_length=2, null=True, verbose_name='Код ПП')),
                ('pp_answer', models.JSONField(blank=True, default=dict)),
                ('lead_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='id лида')),
            ],
        ),
        migrations.CreateModel(
            name='OldLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('url', models.URLField()),
                ('image', models.ImageField(max_length=200, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Источник трафика')),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='краткое название eng')),
                ('icon_html', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код иконки html')),
            ],
            options={
                'verbose_name': 'Источник трафика',
                'verbose_name_plural': 'Источники трафика',
            },
        ),
        migrations.CreateModel(
            name='RootDomain',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.domain')),
            ],
            bases=('office.domain',),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beget_id', models.IntegerField()),
                ('site_name', models.CharField(max_length=99)),
                ('title', models.CharField(default='None', max_length=200, verbose_name='Заголовок сайта')),
                ('check_status', models.CharField(choices=[('Не проверен', 'Не проверен'), ('Ошибка', 'Ошибка'), ('Замечание', 'Замечание'), ('Все ок', 'Все ок')], default='Не проверен', max_length=200, verbose_name='Статус проверки сайта')),
                ('check_data', models.JSONField(blank=True, default=dict, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('is_camp_run', models.BooleanField(default=False)),
                ('is_cloac', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.employee')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.site'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=299, null=True, verbose_name='Название кампании')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('daily', models.CharField(blank=True, max_length=12, null=True, verbose_name='Дневной бюджет')),
                ('pixel', models.CharField(blank=True, default='', max_length=20, verbose_name='Пиксель кампании')),
                ('cab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.cabinet', verbose_name='Кабинет запуска')),
                ('geo', models.ManyToManyField(to='office.Country', verbose_name='Гео запуска')),
                ('land', models.ManyToManyField(to='office.Domain', verbose_name='Запускаемая ссылка')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.campaignstatus')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.domain', verbose_name='Закрепленный домен'),
        ),
        migrations.AddField(
            model_name='account',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='office.trafficsource'),
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('domain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='office.domain')),
                ('root_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.rootdomain')),
            ],
            bases=('office.domain',),
        ),
    ]
