# Generated by Django 3.2.2 on 2021-08-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=99)),
                ('domain', models.URLField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
